apiVersion: v1
kind: PersistentVolume
metadata:
  name: qpp-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/case"
