apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app-claim0
  name: app-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}


apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector: 
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - args:
        - gunicorn
        - -w
        - "4"
        - application:application
        - --reload
        - --bind
        - 0.0.0.0:3000
        env:
        - name: MYSQL_INSTANCE_NAME
          value: app
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: db
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: MYSQL_USERNAME
          value: root
        image: 415711/case:latest
        name: app
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /case
          name: app-claim0
      restartPolicy: Always
      volumes:
      - name: app-claim0
        persistentVolumeClaim:
          claimName: app-claim0
status: {}
