apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30005
      name: http
  selector:
    io.kompose.service: app
